---
- name: Set up bind
  hosts: bind
  gather_facts: true
  user: centos
  become: true

  roles:
    - bind



# - hosts: bind_master
#   connection: local
#   become: True
#   tasks:
#     - name: Ansible template with_items example.
#       template:
#         src: "{{ item.src }}"
#         dest: "{{ item.dest }}"
#         mode: 0777
#       with_items:
#         - {src: 'templates/named.conf.j2',dest: '/etc/named.conf'}
#         # - {src: 'ex2.j2',dest: '/home/dnpjose/ex_rew2.txt'}
#         # - {src: 'ex3.j2',dest: '/home/dnpjose/ex_rew3.txt'}